#! /bin/sh

sxhkd &
xfce4-panel &
xsetroot -cursor_name left_ptr &
picom &
#set wallpaper, fill with theme color
feh --bg-center -B "#002b36" ~/pacwall/pacwall.png
/home/dennis/.screenlayout/home_normal_screen.sh
volumeicon &
nm-applet &
blueman-tray & 
xfce4-power-manager &

setxkbmap -option grp:alt_shift_toggle gr,us & #switching language shortcut

bspc monitor -d eDP-1 I II III
bspc monitor -d HDMI-1 I II III

bspc config border_width         15
bspc config window_gap         0 
bspc config bottom_padding          21

bspc config normal_border_color     "#001220"
bspc config focused_border_color   "#001220"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
