runtime custom_settings/plugin_list.vim
runtime custom_settings/nerd_tree.vim
runtime custom_settings/indentLine.vim
runtime custom_settings/airline.vim
runtime custom_settings/MatchTagAlways.vim
runtime custom_settings/colors.vim
runtime custom_settings/coc.vim
runtime custom_settings/registers.vim
runtime custom_settings/keybinds.vim
runtime custom_settings/general.vim
runtime custom_settings/devIcons.vim
